### ISSUE TITLE
Godot samples

### ISSUE THREAD

**Issue by lucasteles** [lucasteles/Backdash#26]
Create ports of the monogame samples [`SpaceWar`](https://github.com/lucasteles/Backdash/tree/master/samples/SpaceWar) and [`SpaceWar.Lobby`](https://github.com/lucasteles/Backdash/tree/master/samples/SpaceWar.Lobby) to [Godot](https://godotengine.org/)

WIP: https://github.com/lucasteles/BackdashGodotSample

**Comment by 3da** [comment]
I need this. Would be pleasure to see it.

**Comment by lucasteles** [comment]
@3da just pushed an earlier version 

https://youtu.be/8M8QnTiJZzA

https://github.com/lucasteles/BackdashGodotSample
